orocreate-pkg: finish up installation of script
Signed-off-by: Peter Soetens <peter@thesourceworks.com>

diff --git a/scripts/pkg/orocreate-pkg b/scripts/pkg/orocreate-pkg
--- a/scripts/pkg/orocreate-pkg
+++ b/scripts/pkg/orocreate-pkg
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 
 if [ x$1 = x ]; then
     echo "Creates a new Orocos component package."
@@ -6,18 +6,47 @@ if [ x$1 = x ]; then
     exit 1
 fi
 
+cwd=$(pwd)
+abspath=$(dirname "$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")")
+
 pkgname=$1
-cappkgname=$pkgname
-allcappkgname=$pkgname
+allcappkgname=$(echo $pkgname | tr [:lower:] [:upper:])
+cappkgname=$(echo $allcappkgname | cut -c1)$(echo $pkgname | cut -c2-)
 
-#mkdir $pkgname || { echo "Directory already exists: $pkgname" ; exit 1; }
+# Locate the template directory. First look in orocos/ros roots
+# Default location:
+templatedir=$abspath/../share/orocos-ocl/templates
 
-templatedir=templates
+if [ x$OROCOS_ROOT != x ]; then
+    templatedir=$OROCOS_ROOT/ocl/scripts/pkg/templates
+else
+    if [ x$ROS_ROOT != x ]; then
+	templatedir=$(rospack find ocl)/scripts/pkg/templates
+    fi
+fi
+
+# If not found, look in $abspath or installed paths.
+if [ ! -d $templatedir ]; then
+    if [ -d $abspath/templates ]; then
+	templatedir=$abspath/templates
+    fi
+fi
+
+# final check:
+if [ ! -d $templatedir ]; then
+    echo "Could not find templates at $templatedir !"
+    exit 1
+else
+    echo "Using templates at $templatedir..."
+fi
+
+mkdir $pkgname || { echo "Directory already exists: $pkgname" ; exit 1; }
 
 for i in $templatedir/*; do
     tgtname=$(echo "$(basename $i)" | sed -e "s/pkgname/$pkgname/g;s/Pkgname/$cappkgname/g;")
     cat $i | sed -e "s/@PKGNAME@/$allcappkgname/g;s/@pkgname@/$pkgname/g;s/@Pkgname@/$cappkgname/g;" > $pkgname/$tgtname
 done
 
+echo "Package $pkgname created in directory $cwd/$pkgname"
 exit 0
 
